[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "autoVB"
version = "0.1.4"
description = "A generator of XMVB input file: AutoVB tools"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "pyscf",
    "mokit",
    "rdkit",
    "pyssian",
]

[project.scripts]
xyz2nbo = "autoVB.cli.nbo:autovb_nbo"
nbo2xmi = "autoVB.cli.xmi:autovb_xmi"
autovb = "autoVB.cli.autovb:autovb_main"
autovb_test = "autoVB.cli.autovb_test:autovb_test"
draw_xmo = "autoVB.cli.xmo2svg:xmo2svg"
fch2vb = "autoVB.cli.fch2vb:fch2vb"
fch2xmi = "autoVB.cli.fch2vb:fch2vb"
xmo2json = "autoVB.cli.xmo2json:xmo2json"
xmo2xmi = "autoVB.cli.xmo2xmi:xmo2xmi"
xmo2svg = "autoVB.cli.xmo2svg:xmo2svg"

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = ["src"]
